# Generated by Django 3.1.3 on 2020-11-10 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=30)),
                ('account_number', models.PositiveIntegerField()),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('exp_date', models.DateField(default=datetime.datetime(2023, 11, 10, 0, 52, 50, 670392))),
                ('balance', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=60)),
                ('phone_number', models.PositiveIntegerField()),
            ],
        ),
    ]
