# Generated by Django 3.1.3 on 2020-11-11 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=30)),
                ('account_number', models.PositiveIntegerField()),
                ('issue_date', models.DateField(null=True)),
                ('exp_date', models.DateField(default=datetime.datetime(2023, 11, 11, 3, 7, 21, 106629))),
                ('balance', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=60)),
                ('phone_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
