# Generated by Django 3.1.3 on 2020-11-11 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0004_auto_20201111_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 11, 3, 34, 27, 197879)),
        ),
    ]
